---
global:
  sendAnonymousUsage: true
  checkNewVersion: false

api:
  #insecure: true
  dashboard: true
  #debug: true

log:
  filePath: "/etc/traefik/applog.log"
  format: json
  level: "ERROR"

providers:
  docker:
    #endpoint: unix:///var/run/docker.sock
    endpoint: tcp://dockerproxy:2375
    network: dockerproxynet
    exposedByDefault: false
    watch: true
    swarmMode: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  metrics:
    address: ":9090"
  ping:
    address: ":8082"

ping:
  entryPoint: "ping"

certificatesResolvers:
  cloudflare:
    acme:
      email: contact@fqdn.com
      storage: acme.json
      keyType: EC256
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
