---

x-common: &x-common
  privileged: false
  volumes:
    - /etc/localtime:/etc/localtime:ro
  security_opt:
    - no-new-privileges=true
  tmpfs:
    - /tmp:rw,noexec,nosuid,size=32m
  ulimits:
    nproc: 6144
    nofile:
      soft: 6000
      hard: 12000

services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:edge
    restart: always
    container_name: dockerproxy
    networks:
      - dockerproxynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LOG_LEVEL: info
      # 0 to revoke access / 1 to grant access.
      ## Granted by Default
      EVENTS: 1
      PING: 1
      VERSION: 1
      ## Revoked by Default
      # Security critical
      AUTH: 0
      SECRETS: 0
      # Not always needed
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1 # Traefik, portainer, etc.
      DISTRIBUTION: 0
      EXEC: 0
      IMAGES: 1 # Portainer
      INFO: 1 # Portainer
      NETWORKS: 1 # Portainer
      NODES: 0
      PLUGINS: 0
      SERVICES: 1 # Portainer
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 1 # Portainer
      VOLUMES: 1 # Portainer
      TZ: "Europe/Paris"

  traefik:
    <<: *x-common
    image: traefik:saintmarcelin
    restart: unless-stopped
    container_name: traefik
    networks:
      - dockerproxynet
      - oueb
    ports:
      - target : 80
        published : 80
        protocol: tcp
        mode : host
      - target : 443
        published : 443
        protocol: tcp
        mode : host
    volumes:
      - ./conf/acme.json:/acme.json
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/traefikdynamic:/etc/traefik/dynamic:ro
      - ./logs/traefik.log:/etc/traefik/applog.log
      #- /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: "Europe/Paris"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    mem_limit: 256m
    mem_reservation: 128m
    depends_on:
      - dockerproxy

  giteadb:
    <<: *x-common
    image: rapidfort/postgresql-official:15.5-bullseye
    container_name: giteadb
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pgsql_password
      POSTGRES_DB: giteabase
    networks:
      - backendgitea
    volumes:
      - giteadbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d giteabase -U postgres"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 3
    mem_limit: 256m
    memswap_limit: 256m
    mem_reservation: 128m
    secrets:
      - pgsql_password

  giteadb-pgsql_exporter:
    <<: *x-common
    container_name: giteadb-pgsql_exporter
    image: quay.io/prometheuscommunity/postgres-exporter:v0.13.2
    restart: unless-stopped
    networks:
      - backendgitea
    environment:
      DATA_SOURCE_URI: giteadb:5432?sslmode=disable
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS_FILE: /run/secrets/pgsql_password
    depends_on:
      giteadb:
        condition: service_healthy
    mem_limit: 64m
    memswap_limit: 64m
    mem_reservation: 32m
    secrets:
      - pgsql_password

  gitea:
    <<: *x-common
    container_name: gitea
    image: gitea/gitea:1.21-rootless
    restart: unless-stopped
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: giteadb:5432
      GITEA__database__NAME: giteabase
      GITEA__database__USER: postgres
      GITEA__database__PASSWD__FILE: /run/secrets/pgsql_password
      GITEA__mailer__ENABLED: true
      GITEA__mailer__FROM: no-reply@your-domain.net
      GITEA__mailer__MAILER_TYPE: smtp
      GITEA__mailer__SMTP_ADDR: mail.domain.com
      GITEA__mailer__IS_TLS_ENABLED: true
      GITEA__mailer__USER: no-reply@your-domain.net
      GITEA__mailer__PASSWD__FILE: /run/secrets/smtp_password
      USER_UID: 1000
      USER_GID: 1000
    networks:
      - backendgitea
      - oueb
    volumes:
      - giteadata:/var/lib/gitea
      - ./configGitea:/etc/gitea
    depends_on:
      giteadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    mem_limit: 256m
    memswap_limit: 256m
    mem_reservation: 128m
    secrets:
      - pgsql_password
      - smtp_password

secrets:
  pgsql_password:
    file: .secrets/pgsql_password.txt
  smtp_password:
    file: .secrets/smtp_password.txt

networks:
  backendgitea:

  dockerproxynet:
    name: dockerproxynet
    ipam:
      config:
        - subnet: 172.16.10.0/24

  oueb:

volumes:
  giteadata:
  giteadbdata:
