---

services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:edge
    restart: always
    container_name: dockerproxy
    networks:
      - dockerproxynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LOG_LEVEL: info
      # 0 to revoke access / 1 to grant access.
      ## Granted by Default
      EVENTS: 1
      PING: 1
      VERSION: 1
      ## Revoked by Default
      # Security critical
      AUTH: 0
      SECRETS: 0
      # Not always needed
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1 # Traefik, portainer, etc.
      DISTRIBUTION: 0
      EXEC: 0
      IMAGES: 1 # Portainer
      INFO: 1 # Portainer
      NETWORKS: 1 # Portainer
      NODES: 0
      PLUGINS: 0
      SERVICES: 1 # Portainer
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 1 # Portainer
      VOLUMES: 1 # Portainer
      TZ: "Europe/Paris"

  traefik:
    image: traefik:${TRAEFIKVERSION}
    restart: unless-stopped
    container_name: traefik
    networks:
      - oueb
      - backend
      - dockerproxynet
    ports:
      - target : 80
        published : 80
        protocol: tcp
        mode : host
      - target : 443
        published : 443
        protocol: tcp
        mode : host
    volumes:
      - ./conf/acme.json:/acme.json
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/traefikdynamic:/etc/traefik/dynamic:ro
      - ./logs/traefik.log:/etc/traefik/applog.log
      - /etc/localtime:/etc/localtime:ro
      #- /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: "Europe/Paris"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    mem_limit: 256m
    mem_reservation: 128m
    depends_on:
      - dockerproxy

  portainer:
    image: portainer/${PORTAINERVERSION}
    restart: unless-stopped
    networks:
      - oueb
    depends_on:
      - traefik
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - dataportainer:/data

  redis:
    image: redis:${REDISVERSION}
    restart: unless-stopped
    networks:
      - backend
    command: 
      - redis-server 
      - '--maxmemory 1024mb'
      - '--maxmemory-policy allkeys-lru'
      - '--requirepass 9gX2zjz5vvLB5XoBdmdjAQGFtuRsRZVv'
      - '--appendonly yes'
      - '--bind redis'
    volumes:
      - dataredis:/data
      - /etc/localtime:/etc/localtime:ro

#################################################################################
volumes:
  dataredis:
  dataportainer:

#################################################################################
# docker network create --subnet 172.16.1.0/24 --driver bridge oueb
# docker network create --subnet 192.168.10.0/24 backend
networks:
  oueb:
    external: true
    name: oueb

  backend:
    external: true
    name: backend

  dockerproxynet:
    name: dockerproxynet
    ipam:
      config:
        - subnet: 172.16.10.0/24
