---
http:
  routers:
    rt-traefik:
      entryPoints:
      - websecure
      middlewares:
      - authentification
      service: api@internal
      rule: Host (`traefik.yourhome.local`)
      tls:
        certResolver: letsencrypt

    rt-ghost:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      #service: sc-ghost # Fallback if needed. Maybe we need to loadbalance, if varnish is too long...
      service: sc-varnishGhost
      rule: Host (`ghost.yourhome.local`)
      tls:
        certResolver: letsencrypt
