---
http:
  services:
    sc-ghost:
      loadBalancer:
        servers:
        - url: "http://ghost:2368"

    sc-varnishGhost:
      loadBalancer:
        servers:
          - url: "http://varnish:80"
