---

services:
  sqlwp:
    image: mariadb:${MARIADBVERSION}
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./conf/custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf
      - /etc/localtime:/etc/localtime:ro
      - datasqlwp:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOT}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}
 
  nginxwp:
    image: nginx:${NGINXVERSION}
    restart: unless-stopped
    networks:
      - oueb
      - backend
    volumes:
      - datawp:/var/www/html
      - datanginxlogs:/var/log/nginx/
      - /etc/localtime:/etc/localtime:ro
      - ./conf/nginxwp:/etc/nginx/

  wp:
    image: wordpress:${WPVERSION}
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - /etc/localtime:/etc/localtime:ro
      - datawp:/var/www/html
    depends_on:
      - sqlwp
    environment:
      WORDPRESS_DB_HOST: sqlwp
      WORDPRESS_DB_USER: ${MYSQLUSER}
      WORDPRESS_DB_PASSWORD: ${MYSQLPASSWORD}
      WORDPRESS_DB_NAME: ${MYSQLDB}
      WORDPRESS_TABLE_PREFIX: ${MYSQLTABLEPREFIX}

volumes:
  datasqlwp:
  datanginxlogs:
  datawp:

#################################################################################
# docker network create --subnet 172.16.1.0/24 --driver bridge oueb
# docker network create --subnet 192.168.10.0/24 backend
networks:
  oueb:
    external: true
    name: oueb

  backend:
    external: true
    name: backend
