---
http:
  routers:
    rt-traefik:
      entryPoints:
      - websecure
      middlewares:
      - authentification
      service: api@internal
      rule: Host (`traefik.yourhome.local`)
      tls:
        certResolver: letsencrypt

    rt-pihole:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: sc-pihole
      rule: Host (`pihole.yourhome.local`)
      tls:
        certResolver: letsencrypt

udp:
  routers:
    udp-pihole:
      entryPoints:
      - udpdns
      service: sc-pihole-udp
